services:
  - redis-server
before_install:
  - git submodule update --init --recursive
  - make qless-core
  - sudo apt-get install -y libevent-dev python-all-dev python3-all-dev
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install: pip install tox tox-travis
script: tox
cache:
  directories:
    - .tox
    - $HOME/.cache/pip
